UI Scripting, dvars cfg file, basic stats menu
momo5502/boiii pull request #154
Opened 2023-02-12 18:59 UTC by JariKCoding

- Loads lua files from data/ui_scripts
- Supports overriding stock files, just use the same folder/file structure inside the ui_scripts folder as the file you're overriding
- Game now writes dvars to config.cfg in the players/user folder
- Adds a basic stats menu in the public match lobby for enabling/disabling unlocking blackmarket loot.
- Adds a dvar to enable/disable the execution of unsafe lua functions (IO, loading DLL files, accessing shell, ...)
- Shows a stack trace on lua errors instead of "UI Error 0x234234" and removed delay
- Adds luiReload command

2023-02-12 19:17 UTC, momo5502 commented
This is a fucking huge PR. Thank you so much for your contribution. Probably won't have time to review it today, but maybe tomorrow

2023-02-13 06:48 UTC, momo5502 requested changes

2023-02-13 06:48 UTC, momo5502 commented on src/client/component/dvars.cpp
> +			dvar->debugName = dvar_name; // TODO: gives access violation error
What's the TODO here?

2023-02-13 06:48 UTC, momo5502 commented on src/client/component/dvars.cpp
> +			//dvar_register_new_hook.create(0x1422C5330_g, dvar_register_new_stub);
Is this needed? If not, please remove the commented line

2023-02-13 06:48 UTC, momo5502 commented on src/client/component/dvars.cpp
> +			scheduler::execute(scheduler::pipeline::dvars_loaded);
What if one schedules a callback after this was triggered? It's gonna starve. Maybe adding handling that if the callback has been dispatched here, future registrations will immediately fire.

2023-02-13 06:48 UTC, momo5502 commented on src/client/component/ui_scripting.cpp
> +				// TODO: Is it possible to do this with a confirm dialog? Doing this in LUI seems unsafe to me because mods will be able to change this aswell
Good point

2023-02-13 06:48 UTC, momo5502 commented on src/client/component/ui_scripting.cpp
> +			lua_cod_getrawfile_hook.create(0x141F0F880_g, lua_cod_getrawfile_stub);
What about the dedi tho. Doesn't it also have that LUA VM running?

2023-02-13 06:48 UTC, momo5502 commented on src/client/game/game.cpp
> +		return host_library;
Not sure if you need this to be public, because at any point within any compontent default constructed utils::nt::library objects will hold what you need. This is just relevant for code that executes before the game has been mapped and the main module has been swapped.

2023-02-13 06:48 UTC, momo5502 commented on src/client/game/ui_scripting/execution.cpp
> +//#include "component/console.hpp"
Remove pls

2023-02-13 06:48 UTC, momo5502 commented on src/client/game/ui_scripting/script_value.hpp
> +		hks_object value_{};
doesn't this need any refcounting or so, to make sure it lives long enough?

2023-02-13 06:48 UTC, momo5502 commented on src/client/game/ui_scripting/script_value.cpp
> +	script_value::script_value(const std::string& value)
what's when this string dies? who owns the memory?

2023-02-13 06:48 UTC, momo5502 commented on src/client/game/ui_scripting/script_value.cpp
> +	script_value::script_value(const lightuserdata& value)
same here, when lightuserdata gets destroyed, what happens?

2023-02-13 06:48 UTC, momo5502 commented on src/client/game/ui_scripting/script_value.cpp
> +	{
same here

2023-02-13 21:46 UTC, JariKCoding commented on src/client/component/ui_scripting.cpp
> +			lua_cod_getrawfile_hook.create(0x141F0F880_g, lua_cod_getrawfile_stub);
The dedi does run the lua VM but for a different purpose. The normal client uses 2 states with the lua vm, one for the UI and one for the lobby. The lobby one is used by internal workings for lobby navigation, matchmaking and other events in the main menu. The UI state is used for LUI to handle menus, which is the main scope for this pull request. The dedi however doesn't have the UI state since it doesn't have an actual UI so IMO this is out of scope.

2023-02-13 21:46 UTC, JariKCoding commented on src/client/game/ui_scripting/script_value.hpp
> +		hks_object value_{};
I don't know what you mean exactly with this as my C++ knowledge is limited. I took this script from one of the S1X which I assumed worked fine. Same for the next 3 comments.

2023-02-13 21:48 UTC, JariKCoding commented on src/client/component/ui_scripting.cpp
> +				// TODO: Is it possible to do this with a confirm dialog? Doing this in LUI seems unsafe to me because mods will be able to change this aswell
I thought about using some other UI library like imgui for this, instead of just showing a warning and letting the user edit the cfg themselves. Do you have any ideas how I can improve on this or do we consider this resolved for now?

2023-02-13 21:49 UTC, JariKCoding commented on src/client/component/dvars.cpp
> +			scheduler::execute(scheduler::pipeline::dvars_loaded);
I'll have a look at this

2023-02-14 06:52 UTC, mjkzy commented on src/client/component/dvars.cpp
> +			dvar->debugName = dvar_name; // TODO: gives access violation error
probably TODO: fix lol

2023-02-14 07:03 UTC, mjkzy commented on src/client/component/ui_scripting.cpp
> +				// TODO: Is it possible to do this with a confirm dialog? Doing this in LUI seems unsafe to me because mods will be able to change this aswell
> I thought about using some other UI library like imgui for this, instead of just showing a warning and letting the user edit the cfg themselves. Do you have any ideas how I can improve on this or do we consider this resolved for now?

this was a shitty and old solution i did on MWR for doing a yes/no confirmation popup from the client. i later learned you don't need to do stuff like `state->m_apistack.base[0].v.boolean` and such, and blah blah blah

https://github.com/h1-mod/h1-mod/commit/de26138f5b3a03d3caf0bfc79862d3b3a58ceb94#diff-ac64f4a15a0312e949645ecdf58d332ca1cacbce6a9ba21cdebc9cf19cad69a6R310-R335

2023-02-14 07:35 UTC, JariKCoding commented on src/client/component/ui_scripting.cpp
> +				// TODO: Is it possible to do this with a confirm dialog? Doing this in LUI seems unsafe to me because mods will be able to change this aswell
I've also thought about this solution, but it also seems unsafe to me. A mod can still just override whatever confirmation dialog it's using and whenever it's called, check for the title and if it's the right one run the callback immediately instead of showing the dialog.

2023-02-15 09:14 UTC, momo5502 commented on src/client/game/ui_scripting/script_value.cpp
> +	script_value::script_value(const std::string& value)
this is completely unsafe. it will have to be rewritten. but let's do it like this. we're gonna merge this anyways, and i'll rewrite this asap

2023-02-15 09:16 UTC, momo5502 commented on src/client/component/dvars.cpp
> +			scheduler::execute(scheduler::pipeline::dvars_loaded);
nah, fuck it. i'll fix this. i want this PR to be merged.

2023-02-15 09:18 UTC, momo5502 commented on src/client/component/ui_scripting.cpp
> +				// TODO: Is it possible to do this with a confirm dialog? Doing this in LUI seems unsafe to me because mods will be able to change this aswell
I mean who cares about the dialog, if you have to manually adjust the players/user/config.cfg. anyways for shit to work

2023-02-15 09:18 UTC, momo5502 commented on src/client/component/ui_scripting.cpp
> +				// TODO: Is it possible to do this with a confirm dialog? Doing this in LUI seems unsafe to me because mods will be able to change this aswell
if mods kill the dialog, then shit will still not work and leave users confused and think their mod is broken, so it's counterproductive

2023-02-15 09:19 UTC, momo5502 approved these changes
Approved, but will be merged later. Scheduler starving and script value UAFs will need immediate fixes after a merge.

2023-02-15 18:29 UTC, fedddddd commented on src/client/game/ui_scripting/script_value.hpp
> +		hks_object value_{};
> doesn't this need any refcounting or so, to make sure it lives long enough?

The reference is added in `hks_object::assign` with `game::hks::hksi_luaL_ref`

2023-02-15 18:29 UTC, fedddddd commented on src/client/game/ui_scripting/script_value.cpp
> +	script_value::script_value(const std::string& value)
> what's when this string dies? who owns the memory?

It gets copied to the lua memory

2023-02-15 18:31 UTC, fedddddd commented on src/client/game/ui_scripting/script_value.cpp
> +	script_value::script_value(const lightuserdata& value)
It's not supposed to, lightuserdata is used to move C pointers in lua, for example, RegisterMaterial returns a Material pointer

2023-02-16 17:16 UTC, momo5502 commented on src/client/game/ui_scripting/script_value.cpp
> +	script_value::script_value(const std::string& value)
yeah, but the other ones? who owns them?

2023-02-16 17:16 UTC, merged

2023-02-16 17:26 UTC, fedddddd commented on src/client/game/ui_scripting/script_value.cpp
> +	script_value::script_value(const std::string& value)
Not sure which ones you're referring to, if you mean table, function & userdata they are all owned by lua and they are all referenced the same way as hks_object

2023-02-16 17:28 UTC, momo5502 commented on src/client/game/ui_scripting/script_value.cpp
> +	script_value::script_value(const std::string& value)
nvm, i see it now, the constructors create HksObject POD objects, but internally the script_value holds hks_object objects which perform the necessary reference counting/ownership work. but man, naming them nearly identical makes that super hard to spot as a reviewer.