Change server console window title to server name
momo5502/boiii pull request #187
Opened 2023-02-16 22:19 UTC by Brentdevent

Resolves #164

2023-02-16 22:38 UTC, diamante0018 commented on src/client/component/console.cpp
> +					const auto server_name = game::Dvar_FindVar("live_steam_server_name")->current.string;
Is this dvar always guaranteed to be registered, in other words, no nullptr check in ret val of Dvar_FindVar?

2023-02-16 22:52 UTC, Brentdevent commented on src/client/component/console.cpp
> +					const auto server_name = game::Dvar_FindVar("live_steam_server_name")->current.string;
Pretty sure it gets registered everytime, but will add a check just to be sure 👍🏼

2023-02-17 06:55 UTC, momo5502 requested changes

2023-02-17 06:55 UTC, momo5502 commented on src/client/component/console.cpp
> +				}, scheduler::pipeline::main);
please don't do this every frame, do it only every second or so

this could also be extend to player count/max players

2023-02-17 19:55 UTC, Brentdevent commented
I tried adding the bot count to the infoResponse as well:

https://github.com/momo5502/boiii/blob/29095b0224ed2a0b172192e1a30dcf9c712cd781/src/client/component/getinfo.cpp#L89

But for some reason it disconnected me with some error code.

2023-02-17 20:03 UTC, diamante0018 commented on src/client/game/symbols.hpp
> +	WEAK symbol<void(uint32_t localClientNum, ControllerIndex_t controllerIndex, const char* buffer)> Cbuf_ExecuteBuffer{
I do tho think these should be a signed integer and not unsigned although it wouldn't make sense for the client number to be negative. So I'm split on this one. Momo probably knows better

2023-02-17 20:18 UTC, Brentdevent commented on src/client/game/symbols.hpp
> +	WEAK symbol<void(uint32_t localClientNum, ControllerIndex_t controllerIndex, const char* buffer)> Cbuf_ExecuteBuffer{
Yep, I was not sure myself. I'll change if necessary.

2023-02-18 05:55 UTC, momo5502 commented on src/client/game/symbols.hpp
> +	WEAK symbol<void(uint32_t localClientNum, ControllerIndex_t controllerIndex, const char* buffer)> Cbuf_ExecuteBuffer{
the original type is an enum, of which the underlying type is an int, so i'd prefer int

2023-02-18 05:58 UTC, momo5502 requested changes

2023-02-18 05:58 UTC, momo5502 commented on src/client/component/dedicated_info.cpp
> +				if (sv_running && sv_running->current.enabled)
change this to an early return please, the nesting is quite deep here already

2023-02-18 05:58 UTC, momo5502 commented on src/client/component/dedicated_info.cpp
> +				if (sv_running && sv_running->current.enabled)
also if the server is not running, reflecting that in the title might make sense, instead of displaying the previous info, doesn't it?

2023-02-18 05:58 UTC, momo5502 commented on src/client/component/dedicated_info.cpp
> +				if (sv_running && sv_running->current.enabled)
maybe extracting everything in a function as well might be cleaner

2023-02-18 09:09 UTC, Brentdevent commented on src/client/component/dedicated_info.cpp
> +				if (sv_running && sv_running->current.enabled)
Yep, you're correct will change it 👍🏼

2023-02-18 14:04 UTC, momo5502 approved these changes
Formatting seems off, but i'll fix it myself

2023-02-18 14:09 UTC, merged