don't make script errors fatal error
momo5502/boiii pull request #236
Opened 2023-02-25 03:35 UTC by mjkzy

2023-02-25 06:17 UTC, momo5502 commented on src/client/component/client_patches.cpp
> +			}
good practice before com error, not sure if intentional, but very good to scope

2023-02-25 06:17 UTC, momo5502 commented on src/client/component/client_patches.cpp
> +			utils::hook::call(0x1412CAC4D_g, script_errors_stub);
what about the dedi?

2023-02-25 06:18 UTC, mjkzy commented
oh yeah, forgot to do dedi. will do that inna bit

On Sat, Feb 25, 2023 at 12:17 AM Maurice Heumann ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In src/client/component/client_patches.cpp
> <https://github.com/momo5502/boiii/pull/236#discussion_r1117874460>:
>
> > +			{
> +				va_list ap;
> +				va_start(ap, fmt);
> +				vsnprintf_s(buffer, sizeof(buffer), _TRUNCATE, fmt, ap);
> +				va_end(ap);
> +			}
>
> good practice before com error, not sure if intentional, but very good to
> scope
> ------------------------------
>
> In src/client/component/client_patches.cpp
> <https://github.com/momo5502/boiii/pull/236#discussion_r1117874487>:
>
> > @@ -82,6 +96,9 @@ namespace client_patches
>  			utils::hook::set(0x15AAEB254_g, mixer_open_stub);
>
>  			preload_map_hook.create(0x14135A1E0_g, preload_map_stub);
> +
> +			// don't make script errors fatal error
> +			utils::hook::call(0x1412CAC4D_g, script_errors_stub);
>
> what about the dedi?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/momo5502/boiii/pull/236#pullrequestreview-1314458830>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APLEL63PKCKD4GSP43J3ND3WZGPX5ANCNFSM6AAAAAAVHSWKGE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-02-25 06:19 UTC, mjkzy commented on src/client/component/client_patches.cpp
> +			utils::hook::call(0x1412CAC4D_g, script_errors_stub);
will add dedi support in a bit

2023-02-26 06:24 UTC, momo5502 commented on src/client/component/patches.cpp
> +			game::Com_Error(game::ERROR_SCRIPT_DROP, "%s", buffer);
the address for com_error for dedis is not yet added in symbols.hpp!

2023-02-26 06:25 UTC, momo5502 commented on src/client/component/patches.cpp
> +			utils::hook::call(game::select(0x1412CAC4D_g, 0x140158EB2_g), script_errors_stub);
select doesn't require the _g literal

2023-02-26 06:26 UTC, momo5502 requested changes
i wish the formatting was in a separate PR, that would make it easier to review and properly separate the concerns

2023-02-26 09:41 UTC, mjkzy commented on src/client/component/patches.cpp
> +			game::Com_Error(game::ERROR_SCRIPT_DROP, "%s", buffer);
ah poop i should have looked into this more, sorryyyy

2023-02-26 10:18 UTC, momo5502 approved these changes

2023-02-26 10:18 UTC, merged