better discord rpc
momo5502/boiii pull request #244
Opened 2023-02-27 01:25 UTC by mjkzy

- needs a way to get the amount of clients in your game (i'm not familiar with the structs)
- discord application ID needs changed

2023-02-27 05:58 UTC, momo5502 commented on src/client/component/discord.cpp
> +				static char clean_hostname[0x80] = {0};
why static char of 8? why not std::string? why static?

2023-02-27 06:00 UTC, momo5502 commented on src/client/component/discord.cpp
> +		DiscordRichPresence discord_presence{};
why is this a global?

2023-02-27 06:03 UTC, momo5502 requested changes

2023-02-27 06:03 UTC, momo5502 commented on src/client/component/discord.cpp
> +			Discord_Initialize("1079371545266364516", &handlers, 1, nullptr);
why did you change the id? instead of requesting me to make the changes on the proper app

2023-02-27 06:03 UTC, momo5502 commented on src/client/component/discord.cpp
> +		}
why static member functions?

2023-02-27 06:03 UTC, momo5502 commented on src/client/component/party.cpp
> +		std::string hostname{};
pretty sure the game already stores this. like iw4x has it in the scoreboard server info.

2023-02-27 06:03 UTC, momo5502 commented on src/client/component/discord.cpp
> +			}, scheduler::pipeline::main);
that's a bit weird, that can be cleaned up

2023-02-27 06:03 UTC, momo5502 commented on src/client/component/discord.cpp
> +		void update_discord()
this function is quite long and has a lot of code. it can be split up

2023-02-27 06:40 UTC, mjkzy commented on src/client/component/discord.cpp
> +				static char clean_hostname[0x80] = {0};
this is all code from h1-mod, keep that in mind :P

also, i think its because of utils::string::strip
https://github.com/mjkzy/boiii/blob/discord/src/client/component/discord.cpp#L53

2023-02-27 06:42 UTC, mjkzy commented on src/client/component/discord.cpp
> +		}
idk, this is from s1x https://github.com/XLabsProject/s1x-client/blob/develop/src/client/component/discord.cpp#L152

2023-02-27 06:43 UTC, mjkzy commented on src/client/component/discord.cpp
> +			}, scheduler::pipeline::main);
same as above https://github.com/XLabsProject/s1x-client/blob/develop/src/client/component/discord.cpp#L130

2023-02-27 06:43 UTC, mjkzy commented on src/client/component/discord.cpp
> +		void update_discord()
same has above. https://github.com/XLabsProject/s1x-client/blob/develop/src/client/component/discord.cpp#L34
however, i agree

2023-02-27 10:39 UTC, diamante0018 commented on src/client/component/discord.cpp
> +				static char clean_hostname[0x80] = {0};
It's not Static on xlabs and it works fine. You just have to call the discord API function before the stack is cleaned by the epilogue code at the function end. That's what I did on iw4x, iw6x, s1x

2023-02-27 10:41 UTC, diamante0018 commented on src/client/component/discord.cpp
> +				static char clean_hostname[0x80] = {0};
Why should we keep in mind this is code from h1? It shouldn't really matter where it's from

2023-02-27 10:51 UTC, diamante0018 reviewed
While I can't blame anyone for taking inspiration from S1x, if the code can be improved it should and then s1x shall receive an upgrade to the code as well. Replying with links to the s1x code as a means to justify why code shouldn't be changed is not the right way to go forward (that's how I interpreted it). I can update the xlabs clients after this pr is finalized with the new and improved code

2023-02-27 11:02 UTC, Rackover reviewed
nothing more to say than what's already been said, just these tiny bit of strings lying around in code that could be put in defines/constexpr in CPP

2023-02-27 11:02 UTC, Rackover commented on src/client/component/discord.cpp
> +			Discord_Initialize("1079371545266364516", &handlers, 1, nullptr);
Move application ID to a named constexpr at the beginning of the file

2023-02-27 11:02 UTC, Rackover commented on src/client/component/discord.cpp
> +			Discord_Initialize("1079371545266364516", &handlers, 1, nullptr);
(most of the strings i see here - "Main menu", "Private match" could be moved to constexpr variables the same for easier edit)

2023-02-27 11:05 UTC, mjkzy commented
will prob reopen this later, left it as draft because i wasn't ready for reviews yet and was just having the RPC at least working but thank you guys :)

2023-02-27 11:05 UTC, closed without merging

2023-02-28 19:42 UTC, mjkzy commented on src/client/component/discord.cpp
> +		DiscordRichPresence discord_presence{};
how should i do this? i do it so the `update_discord` and `ready` functions can both use the variable

2023-02-28 19:43 UTC, mjkzy commented on src/client/component/party.cpp
> +		std::string hostname{};
i looked into iw4x discord RPC and just how hostname stuff is handled and they do the same solution by just getting the hostname stored from the infostring

2023-02-28 19:45 UTC, mjkzy commented on src/client/component/discord.cpp
> +			}, scheduler::pipeline::main);
how do you want me to clean this up? we only run the discord RPC stuff when the main thread is ready (which makes sense because `update_discord` calls game functions that become relevant after that) and then we just call that same function ervery 5 seconds. and then the Discord_RunCallbacks is necessary for keeping Discord up to date