More bot functionality in ranked matches, public lobby modification for games against bots.
momo5502/boiii pull request #310
Opened 2023-03-09 16:44 UTC by joseupp

-Modified the gsc so that the bots connect to ranked games.
-Added more killstreak to bots and loot weapons.
-Add start game button in public lobby.
-Add menu setup bots in public lobby.

2023-03-09 16:55 UTC, momo5502 commented
looks good to me, but maybe you can have a look at it, @JarivdKaap

2023-03-09 18:36 UTC, diamante0018 requested changes
Were these files originally taken from a dump of some sort like the official mod tools?

2023-03-09 18:36 UTC, diamante0018 commented on data/ui_scripts/stats/__init__.lua
> +    AddSmallButton( f27_arg0, f27_arg1, CoD.LobbyButtons.SETTING_UP_BOTS ) --Bot setting menu in public lobby
format

2023-03-09 18:36 UTC, diamante0018 commented on data/ui_scripts/stats/__init__.lua
> +    OpenPopup( menu, "GameSettings_Bots", controller )
formatting seems off.

2023-03-09 18:36 UTC, diamante0018 commented on data/ui_scripts/stats/__init__.lua
> +	--Engine.SetDvar( "bot_difficulty", 3 )
if not needed remove commented out code?

2023-03-09 19:14 UTC, joseupp commented
> Were these files originally taken from a dump of some sort like the official mod tools?

The gsc files are from the official mod tools, the code added to the lua files are from a dump with CoDLuaDecompiler

2023-03-09 19:26 UTC, JariKCoding requested changes
Nice pr, seems to work fine.

2023-03-09 19:26 UTC, JariKCoding commented on data/ui_scripts/stats/__init__.lua
> +	Engine.SetDvar( "bot_enableWallrun", 0 ) --vote map at start lobby, switch
This doesn't seem to do anything to the voting

2023-03-09 19:26 UTC, JariKCoding commented on data/ui_scripts/stats/__init__.lua
> +	if Dvar.bot_enableWallrun:get() == false then
I recommend moving the bot_enableWallrun dvar change to gsc, seems weird do this setting on the UI side

2023-03-09 19:26 UTC, JariKCoding commented on data/ui_scripts/stats/__init__.lua
> +	if not DisableBlackMarket() then
Setting up bots is only available when the black market is not disabled? Remove the if statement here. Also you need to disable the button when you aren't the host

2023-03-09 19:26 UTC, JariKCoding commented on data/scripts/mp/bots/_bot_loadout.gsc_raw
> +		//case "WEAPON_SHOTGUN_PUMP":
Is there a reason why you disabled some weapons?

2023-03-09 19:31 UTC, diamante0018 commented on data/scripts/mp/bots/_bot_loadout.gsc_raw
> +		//case "WEAPON_SHOTGUN_PUMP":
Perhaps it should be possible to add replacefunc like on pluto/xlabs clients?
I'm not a fan of these huge pull requests that modify entire game files and we risk merging stuff like this. luckily you noticed it.

2023-03-09 19:40 UTC, JariKCoding commented on data/scripts/mp/bots/_bot_loadout.gsc_raw
> +			}
You seemed to have commented out all other instances in the file like this where IsItemLocked is called but not this one, is that right?

2023-03-09 20:38 UTC, joseupp commented on data/ui_scripts/stats/__init__.lua
> +	Engine.SetDvar( "bot_enableWallrun", 0 ) --vote map at start lobby, switch
Without this line it does not work correctly if it is loaded automatically when entering the lobby, the line is set as a switch so that it is executed only once, Engine.Exec( nil, "LobbyStopDemo" ), If this is not done, pressing any button or voting on a map will run again, resetting the time counter and voting, I imagine there will be another way to do this but I don't know.
Ideally, the lobby should be patched so that it works automatically and so none of this is necessary. I hope you get it.

2023-03-09 20:38 UTC, joseupp commented on data/ui_scripts/stats/__init__.lua
> +	if Dvar.bot_enableWallrun:get() == false then
As I have told you, this is as a switch.

2023-03-09 20:38 UTC, joseupp commented on data/ui_scripts/stats/__init__.lua
> +	if not DisableBlackMarket() then
It is always available, I will remove the line you comment

2023-03-09 20:38 UTC, joseupp commented on data/scripts/mp/bots/_bot_loadout.gsc_raw
> +		//case "WEAPON_SHOTGUN_PUMP":
Yes, but it's a personal reason, if the weapon is a shotgun the bot has to get too close so it's very easy to eliminate it. it's just that.

2023-03-09 20:38 UTC, joseupp commented on data/scripts/mp/bots/_bot_loadout.gsc_raw
> +			}
yes

2023-03-09 21:20 UTC, mjkzy commented on data/ui_scripts/stats/__init__.lua
> +	if Dvar.bot_enableWallrun:get() == false then
i think his point still stands

2023-03-09 21:28 UTC, mjkzy commented on data/ui_scripts/stats/__init__.lua
> +    AddSmallButton( f27_arg0, f27_arg1, CoD.LobbyButtons.SETTING_UP_BOTS ) --Bot setting menu in public lobby
https://github.com/joseupp/boiii/pull/1

2023-03-09 21:41 UTC, JariKCoding commented on data/ui_scripts/stats/__init__.lua
> +	Engine.SetDvar( "bot_enableWallrun", 0 ) --vote map at start lobby, switch
Using a random dvar as a switch seems like a bad idea to me

2023-03-09 21:48 UTC, JariKCoding commented on data/ui_scripts/stats/__init__.lua
> +	Engine.SetDvar( "bot_enableWallrun", 0 ) --vote map at start lobby, switch
You can just make a local variable outside the CoD.LobbyMenus.MPButtonsOnlinePublic function and change that to true/false

2023-03-10 07:37 UTC, joseupp commented on data/ui_scripts/stats/__init__.lua
> +	Engine.SetDvar( "bot_enableWallrun", 0 ) --vote map at start lobby, switch
> You can just make a local variable outside the CoD.LobbyMenus.MPButtonsOnlinePublic function and change that to true/false

I don't know how to do what you're telling me, could you tell me how to do it, I want to learn. Thank you.

2023-03-10 08:34 UTC, momo5502 commented on data/ui_scripts/stats/__init__.lua
> +	--Engine.SetDvar( "bot_difficulty", 3 )
comment here makes sense i think

2023-03-11 10:16 UTC, closed without merging

2023-03-11 10:21 UTC, joseupp commented
These changes are no longer compatible with @JariKCoding's new PR

2023-03-11 10:28 UTC, joseupp commented
Changes I make to ui script are no longer compatible with @JariKCoding's new PR