Enable bots in ranked match
momo5502/boiii pull request #325
Opened 2023-03-12 12:42 UTC by joseupp

The following improvements have been added.

1. Bots work on public matches and dedicated servers.
2. Bots use all specialists.
3. Bots can use all weapons and all scorestreak they have available (including loot weapons) in ranked match.
4. Added two scorestreak to bots (ai tank and remote missile).
5. Launch match button has been added in public lobby.
6. Game setup button has been added in public lobby.
7. Vote map is now active when starting public lobby.
8. Launch match button has been added in arena lobby.
9. Added customize bots button in arena lobby.

2023-03-12 14:57 UTC, momo5502 commented
@JariKCoding, can you have a look?

2023-03-12 17:06 UTC, momo5502 commented
> For anyone else reviewing, I requested some changes (https://github.com/joseupp/boiii/pull/1).
> 
> - added a function to enable the map vote widget with working on/off switch. Since the match does not automatically start at the end of the timer I set this to disabled for initial release.
> - removed a few buttons that were unnecessary in this menu: black market, leaderboard, server description, and redundant game type selection.
> - general cleanup and formatting
> 
> Also, great work Joseupp! I have been testing this for a few days now and I think users will be very pleased with this update.

removing buttons that you consider unnecessary is not a good thing to do. nobody knows if black market is going to be supported.

2023-03-12 19:17 UTC, momo5502 commented
i honestly feel all this should be different PRs. the fact that you have to put "and more" in the title shows that there is too much going on here. that makes it harder to review. i consider separating concerns into different PRs

2023-03-12 19:22 UTC, joseupp commented
> i honestly feel all this should be different PRs. the fact that you have to put "and more" in the title shows that there is too much going on here. that makes it harder to review. please consider separating concerns into different PRs.
> 
> Unless, jari can review it. because i don't feel qualified to review this pr

It's no problem for me, but how do I separate them? I don't know how to do it.
However, if it's okay with you, we'll wait for @JariKCoding to review it.

2023-03-12 21:10 UTC, JariKCoding requested changes
Pretty decent, for the formatting/linting of lua I'll have a talk with mikz how we can improve that cuz that's a mess atm.

2023-03-12 21:10 UTC, JariKCoding commented on data/ui_scripts/stats/__init__.lua
> +    end
We don't want to use global variables as BO3 doesn't like them very much, so add the following above the definition of function CoD.LobbyMenus.MPButtonsOnline at line 402: `local MapVote = 0`

2023-03-12 23:08 UTC, joseupp reviewed
Proposed Changes Made

2023-03-12 23:09 UTC, joseupp commented on data/scripts/mp/bots/_bot.gsc_raw
> +}
changed

2023-03-12 23:09 UTC, joseupp commented on data/scripts/mp/bots/_bot.gsc_raw
> +}
changed

2023-03-12 23:09 UTC, joseupp commented on data/scripts/mp/bots/_bot_loadout.gsc_raw
> +		case "WEAPON_BALL":
changed

2023-03-12 23:09 UTC, joseupp commented on data/ui_scripts/stats/__init__.lua
> +	AddSmallButton( f31_arg0, f31_arg1, CoD.LobbyButtons.MP_START_GAME ) --Launch match button
changed

2023-03-12 23:09 UTC, joseupp commented on data/ui_scripts/stats/__init__.lua
> +	AddSpacer( f31_arg1 )
changed

2023-03-12 23:09 UTC, joseupp commented on data/ui_scripts/stats/__init__.lua
>  	--AddLargeButton( f33_arg0, f33_arg1, CoD.LobbyButtons.ZM_GOBBLEGUM_RECIPES )
changed

2023-03-12 23:10 UTC, joseupp commented on data/ui_scripts/stats/__init__.lua
> +--  AddSmallButton( f27_arg0, f27_arg1, CoD.LobbyButtons.SETTING_UP_BOTS ) --Bot setting button in public lobby
changed

2023-03-12 23:15 UTC, joseupp commented on data/ui_scripts/stats/__init__.lua
> +  --Engine.SetDvar( "bot_difficulty", 3 )
I don't think this line should be eliminated, because even if the bot difficulty is changed in the menu, if you go back to search for a match, the difficulty returns to default.

2023-03-12 23:15 UTC, joseupp commented on data/ui_scripts/stats/__init__.lua
> +  --Engine.SetDvar( "bot_difficulty", 3 )
changed

2023-03-12 23:15 UTC, joseupp commented on data/ui_scripts/stats/__init__.lua
> +    end
changed

2023-03-13 06:55 UTC, momo5502 requested changes
please separate changes that are required for your offline rankup and the dedi bots.
so roughly separate gscs from menus, as i don't know if i like the menu changes.

2023-03-13 08:47 UTC, joseupp commented
> please separate changes that are required for your offline rankup and the dedi bots into different PRs so roughly separate gscs from menus, as i don't know if i like the menu changes.

I have separated in 2 PR

2023-03-14 09:17 UTC, joseupp commented
This PR has been split in two, it is no longer needed.

2023-03-14 09:17 UTC, closed without merging