Support all game modes for public matches
momo5502/boiii pull request #328
Opened 2023-03-12 19:51 UTC by WantedDV

- adds all game modes to public lobby selection list
- player limit increased to 18.  You can adjust how many bots spawn with the Bot Settings menu.
- when the game picks a random map it now does so with equal priority across all maps
- old playlists were updated to use all maps of appropriate size, so it no longer rotates the same few maps over and over. 

![gm1](https://user-images.githubusercontent.com/122710241/224566375-0e6d2c64-7757-4baf-8abe-a6bbb8d965d6.PNG)
![gm2](https://user-images.githubusercontent.com/122710241/224566377-aa61a363-bc0a-497f-8246-feddcddaca00.PNG)

2023-03-12 22:27 UTC, JariKCoding commented
Do we want double xp/divinium always enabled? Maybe there's a possibility to make timed events with it enabled to boost player count?

2023-03-13 06:53 UTC, momo5502 commented
> Keep in mind that boiii is designed to use dedicated servers, so the "events" are up to the people hosting servers. There they can customize the options and xp scaling to their liking. This PR is just for playing with bots or friends via direct connection.

yes, that's exactly how it is. which is why i don't know how to feel about this PR. we don't support this. we don't support matchmaking. hence accepting PRs which adjust just that is not in my interest. it will give people the impression we do support it and thus make people request more features. that's not in my interest. if you want to rank up, imo just spin up a dedi. i don't want to support multiple ways of ranking up. also touching the playlists file feels off as well. the playlists is 100% equivalent to the one DW delivers. preserving that feels like an important thing to do.

2023-03-13 16:53 UTC, 4doorsmorehoes commented
I edit the playlist on PlutoT6 the past. even though it did work but the same time it caused issues that broken other T6 game languages to the point that it has a certain playlist issue limit.

@momo5502 I would suggest supporting it as a user custom side boiii/playlist.info but not public one that's ship if you know what I mean.

2023-03-14 09:41 UTC, momo5502 requested changes
You aare changing so many values which I don't know what they do. I highly doubt you know what effect all of these have. If not, please only only change what's necessary. If you do know, please explain each desired change in detail!

2023-03-14 09:41 UTC, momo5502 commented on src/client/resources/dw/playlists_tu32.gz
>  rule zmVialGroups everyone
don't mark the conversation as resolved, if you did not fix this!

2023-03-14 10:05 UTC, joseupp commented
It is best not to modify the original playlist and add this feature made in s1x and iw6x by @diamante0018.
https://github.com/XLabsProject/iw6x-client/commit/20ba1677e46424162cb380593c04c07bf0f6a6ce#diff-30ce8ecdc615ea433fbd40a148d49006e6511de20381121e05093e7eb2dc057a

2023-03-14 11:04 UTC, momo5502 requested changes

2023-03-14 11:04 UTC, momo5502 commented on src/client/resources/dw/playlists_tu32.gz
> -setdvar cg_paintshopWriteDiskCache 0								// Assists with Paintshop streaming
what does this do?

2023-03-14 11:04 UTC, momo5502 commented on src/client/resources/dw/playlists_tu32.gz
> +setdvar lobbySearchSkipUnparkProbability 0
?

2023-03-14 11:04 UTC, momo5502 commented on src/client/resources/dw/playlists_tu32.gz
> +setdvar zmhd_purchase_reward_popup_enabled 0
?

2023-03-14 11:04 UTC, momo5502 commented on src/client/resources/dw/playlists_tu32.gz
> +setdvar probation_version 0
?

2023-03-14 11:04 UTC, momo5502 commented on src/client/resources/dw/playlists_tu32.gz
> +setdvar tu4_enableCodPoints 0
?

2023-03-14 11:04 UTC, momo5502 commented on src/client/resources/dw/playlists_tu32.gz
> +setdvar loot_bundleActive 1
?

2023-03-14 11:04 UTC, momo5502 commented on src/client/resources/dw/playlists_tu32.gz
> +setdvar ui_enableZMHDFeaturedCard 1    // Enables Thermometer widget in ZM shell
?

2023-03-14 11:04 UTC, momo5502 commented on src/client/resources/dw/playlists_tu32.gz
> +rule scr_gunxpscalezm 2
again, why is xpscale still two?

2023-03-14 11:04 UTC, momo5502 commented on src/client/resources/dw/playlists_tu32.gz
> +rule scr_gunxpscalemp 2
no

2023-03-14 11:04 UTC, momo5502 commented on src/client/resources/dw/playlists_tu32.gz
> +rule scr_gunxpscalemp 2
no

2023-03-14 11:04 UTC, momo5502 commented on src/client/resources/dw/playlists_tu32.gz
> +rule scr_gunxpscalemp 2
no

2023-03-14 11:04 UTC, momo5502 commented on src/client/resources/dw/playlists_tu32.gz
> +rule scr_gunxpscalemp 2
no

2023-03-14 11:04 UTC, momo5502 commented on src/client/resources/dw/playlists_tu32.gz
> +rule scr_gunxpscalemp 2
no

2023-03-14 11:04 UTC, momo5502 commented on src/client/resources/dw/playlists_tu32.gz
> +rule scr_gunxpscalemp 2
no

2023-03-14 11:04 UTC, momo5502 commented on src/client/resources/dw/playlists_tu32.gz
> +rule scr_gunxpscalemp 2
no

2023-03-14 11:04 UTC, momo5502 commented on src/client/resources/dw/playlists_tu32.gz
> +rule scr_gunxpscalemp 2
no

2023-03-14 11:04 UTC, momo5502 commented on src/client/resources/dw/playlists_tu32.gz
> +rule scr_gunxpscalemp 2
no

2023-03-14 11:04 UTC, momo5502 commented on src/client/resources/dw/playlists_tu32.gz
> +rule scr_gunxpscalemp 2
no

2023-03-14 11:04 UTC, momo5502 commented on src/client/resources/dw/playlists_tu32.gz
> +rule scr_gunxpscalemp 2
no

2023-03-14 11:49 UTC, momo5502 commented on src/client/resources/dw/playlists_tu32.gz
> -setdvar cg_paintshopWriteDiskCache 0								// Assists with Paintshop streaming
but you have no idea what this really does, if it adds a benefit or if it might even break something in certain cases, so why change it?

2023-03-14 11:49 UTC, momo5502 commented on src/client/resources/dw/playlists_tu32.gz
> +setdvar lobbySearchSkipUnparkProbability 0
if it's not used, then there is no point in changing it. please restore

2023-03-14 11:49 UTC, momo5502 commented on src/client/resources/dw/playlists_tu32.gz
> +setdvar zmhd_purchase_reward_popup_enabled 0
fair

2023-03-14 11:50 UTC, momo5502 commented on src/client/resources/dw/playlists_tu32.gz
> +setdvar probation_version 0
please revert.

2023-03-14 11:51 UTC, momo5502 commented on src/client/resources/dw/playlists_tu32.gz
> +setdvar tu4_enableCodPoints 0
i see no comment after `setdvar tu4_enableCodPoints 0`, not sure where you see the comment they left, but do not change.

2023-03-14 11:52 UTC, momo5502 commented on src/client/resources/dw/playlists_tu32.gz
> +setdvar loot_bundleActive 1
we have no black market, so why change it?

2023-03-17 06:54 UTC, momo5502 commented
You still have not reverted everything i told you to do. Literally the first line has not been reverted even if you said so. This is taking a bit too much time imo. Also i don't like the change. We don't support that. We will probably add the possibility of using a custom playlist. but for now just start a dedi.

2023-03-17 07:13 UTC, momo5502 commented on src/client/resources/dw/playlists_tu32.gz
> -setdvar cg_paintshopWriteDiskCache 0								// Assists with Paintshop streaming
you shouldn't mark things as resolved when in fact they aren't

2023-03-23 12:54 UTC, momo5502 approved these changes

2023-03-23 12:58 UTC, merged