Rawfile dumping overriding
momo5502/boiii pull request #44
Opened 2022-10-05 03:18 UTC by JezuzLizard

2022-10-05 05:08 UTC, momo5502 requested changes
Memory safety needs to be reworked. Rest is fine tho.

2022-10-05 05:08 UTC, momo5502 commented on src/client/component/assets.cpp
> +			}
How is that safe?
You're storing the data in the struct and replacing the buffer pointer. Why memcpy again then? You're memcpy'ing from and to the identical buffer, or am I wrong?
If not, it's even worse, cause then you don't know the size of the buffer you are copying to. So that's either a buffer overflow or a use-after-free after FS_FreeFile. No matter which case of the two, this definitely needs to be reworked to be memory safe.

2022-10-05 17:34 UTC, ineedbots commented on src/client/component/assets.cpp
> +			}
it isn't the same buffer that memcpy is copying to, however, this isnt memory safe,  you need to add some sort of buffer pool and copy the rawfile data into it, and use that for rawfile->buffer

2022-10-05 17:39 UTC, momo5502 commented on src/client/component/assets.cpp
> +			}
Yeah, true, just noticed the result buffer is stored on the `buffer` stack variable. Memcpy'ing in this case is a buffer overflow.

2022-10-05 20:05 UTC, JezuzLizard commented
https://github.com/momo5502/boiii/pull/44/commits/bacdce179845fb706e7fd60ea5f0fc2e8eeb2084 changes rawfile overriding to store the rawfile buffers, and resize them before memcpying. Also an include for unused header file was removed.

2022-10-05 20:28 UTC, diamante0018 requested changes

2022-10-05 20:28 UTC, diamante0018 commented on src/client/game/structs.hpp
> +	enum XAssetType : __int32
I think you should remove the `: __int32` it's from IDA, it's not necessary (int32_t is the default value anyway) and a Microsoft-specific extension.

2022-10-05 20:29 UTC, diamante0018 commented on src/client/component/assets.cpp
> +	void override_rawfile(game::RawFile* rawFile)
Just return early. forcing yourself to write functions with just one return path (end of functions) can be bad and make code harder to read.
```
if (!raw_file)
   return;
   ```

2022-10-05 20:29 UTC, diamante0018 commented on src/client/component/assets.cpp
> +	void override_rawfile(game::RawFile* rawFile)
snake case all variables. I think this is how @momo5502 has styled this project

2022-10-06 07:24 UTC, JezuzLizard commented
https://github.com/momo5502/boiii/pull/44/commits/ccf76aaa29860ac12143936de5baa6664d844548
Changes made:

Add comments, convert all variables to snake_case.

Dumping:
Dump null buffered rawfiles, don't dump referenced rawfiles.

Fixed "Expression: vector subscript out of range" assertion.

Allow overriding null buffer rawfiles.

2022-10-06 08:21 UTC, momo5502 commented on src/client/component/assets.cpp
> +		utils::io::write_file("dump\\"s + rawfile->name, buffer);
std::string buffer(rawfile->buffer, rawfile->len);

You can directly construct an std::string, no need to use memcpy. Just the nullcheck needs to be done

2022-10-06 08:27 UTC, momo5502 commented on src/client/component/assets.cpp
> +			game::FS_FreeFile(buffer);
This indeed fixes the buffer overrun. I think std::map iterators are stable, which means taking their pointer is stable as an insertion does not invalidate said pointer.
However, erasure above seems quite unsafe. Did you assert that the old pointer is definitely unused anymore? E.g. if you are overriding an asset, the old asset may still point to the old element, causing a use after free. Or can potential race conditions occur, eg. through other threads caching/simultaneously accessing the buffer?

2022-10-06 08:27 UTC, momo5502 commented on src/client/component/assets.cpp
> +		}
Do we actually need the other cases, except rawfile?

2022-10-09 20:54 UTC, JezuzLizard commented
New version
Use unipue_ptr instead of vector for rawfile_buffers.
Dump assets by zone filename.

2022-10-17 22:05 UTC, diamante0018 requested changes
Jesus requested me to review this pr so I'm gonna point out everything that bothers me.
A bit of changes before it's merged should be done

2022-10-17 22:05 UTC, diamante0018 commented on src/client/component/assets.cpp
> +		if (num_bytes_read > -1)
`if (num_bytes_read < 0) return;` !

2022-10-17 22:05 UTC, diamante0018 commented on src/client/component/assets.cpp
> +			rawfile->buffer = reinterpret_cast<char*>(rawfile_entry_buffer);
change the type of the container from uint8_t to char if you need to store characters instead of doing weird conversions maybe?
You defined rawfile struct as having one buffer field of type char.

2022-10-17 22:48 UTC, JezuzLizard commented on src/client/component/assets.cpp
> +		if (rawfile->name[0] == ',')
Checking for the comma prevents attempting to dump a referenced asset.

2022-10-17 23:02 UTC, diamante0018 commented on src/client/component/assets.cpp
> +		if (rawfile->name[0] == ',')
Good to know. I guess if this is something that is commonly known it does not need a comment but I had no idea so it might not be obvious

2022-10-17 23:05 UTC, JezuzLizard commented on src/client/game/structs.hpp
> +	enum XAssetType
This enum is correct and can be verified by going to this address in boiii (0x14332A080). This is g_assetNames and the asset names are ordered in the same way as the enum up to 107. The cod_debug.elf's XAssetTypes enum is only missing two assets otherwise its correct. I already added the missing two asset values so the whole enum matches what can be seen here:
![image](https://user-images.githubusercontent.com/26215347/196299549-f123e557-6be9-48f2-8382-93671d4eed6d.png)

2022-10-18 05:47 UTC, momo5502 commented on src/client/component/assets.cpp
> +		std::string buffer{};
i like {} tho, doing that everywhere leads to less uninitialized variables. even though it is unnecessary here, it is good practice imo, if you do it everywhere

2022-10-18 05:48 UTC, momo5502 commented on src/client/component/assets.cpp
> +		if (rawfile->name[0] == ',')
yeah, kinda weird, but it is like that in cod :P

2022-10-18 05:50 UTC, momo5502 commented on src/client/component/assets.cpp
> +			auto rawfile_buffer_iterator = rawfile_buffers.find(rawfile->name);
while i don't like abbreviations, i still aggree here, an iterator is an abstract concept, so the name is kinda meaningless anyways. therefore the shorter the name, the less bloat there is to read

2022-10-18 12:22 UTC, diamante0018 commented on src/client/component/assets.cpp
> +		if (num_bytes_read > -1)
Update the comment as I realized you may prefer `<=0`. Not sure please double check

2022-10-19 03:40 UTC, JezuzLizard commented on src/client/component/assets.cpp
> +		utils::io::write_file("dump\\"s + game::g_load->filename + "\\"s + rawfile->name, buffer);
The assert isn't needed because the game will crash before reaching my code. The only way g_load->filename can be nullptr is if the game tried to load a fastfile with no name.

2022-10-19 03:42 UTC, ineedbots commented on src/client/game/structs.hpp
> +	struct DB_LoadData
what good is the struct if we lose the actual offsets of key data? why would we remove the actual structure of the struct? it seems counter productive to me, especially if needing to reimport the structs.

2022-10-19 03:52 UTC, ineedbots commented on src/client/game/structs.hpp
> +	struct DB_LoadData
at that point, it would be better off not using the struct at all and just use reinterpet_cast<char*>(<BASEADDR> + <MEMBEROFFSET>)

2022-10-19 20:19 UTC, JezuzLizard commented on src/client/component/assets.cpp
> +		if (num_bytes_read > -1)
0 is a valid return value so < 0 is correct. Use case would be if you want to completely nullify what a .cfg file does by removing its contents.

2022-10-19 20:22 UTC, JezuzLizard commented on src/client/component/assets.cpp
> +			rawfile_buffer_iterator = rawfile_buffers.find(rawfile->name);
We need to use the ptr that make_unique created. So we can assign it to the rawfile struct. If it can be done another way please give an example.

2022-10-19 20:23 UTC, JezuzLizard commented on src/client/component/assets.cpp
> +			if (rawfile_buffer_iterator != rawfile_buffers.end())
We need the iterator to manually delete the old buffer if we find it.

2022-10-19 20:24 UTC, JezuzLizard commented on src/client/game/structs.hpp
> +	struct DB_LoadData
I replaced the majority of the unlabeled struct with padding.

2022-10-19 21:42 UTC, JezuzLizard commented
Rebased with upstream. Move assets.cpp to assets folder, move rawfile specific code to rawfile.cpp and rawfile.hpp.

2022-10-20 06:16 UTC, momo5502 requested changes

2022-10-20 06:16 UTC, momo5502 commented on src/client/game/structs.hpp
> +	struct DB_LoadData
as the author of the commit, please don't mark conversations as resolved. the reviewer decides if it's resovled or not. otherwise you could just directly review your own stuff.
but I'm fine with such structs.

2022-10-20 06:16 UTC, momo5502 commented on src/client/component/assets/rawfile.cpp
> +			rawfile_buffers[rawfile->name] = std::make_unique<char[]>(num_bytes_read + 1);
i personally would use std::vector, but char[] is not necessarily wrong. can't decide what's better

2022-10-20 06:16 UTC, momo5502 commented on src/client/component/assets/rawfile.cpp
> +			rawfile_buffers[rawfile->name] = std::make_unique<char[]>(num_bytes_read + 1);
if you want just keep it that way

2022-10-20 06:16 UTC, momo5502 commented on src/client/component/assets/rawfile.cpp
> +REGISTER_COMPONENT(assets::rawfile::component)
why is this a component tho? just move this back to assets? because this is definitely not a component, if that stuff is empty

2022-10-20 06:16 UTC, momo5502 commented on src/client/component/assets/rawfile.cpp
> +			rawfile_buffers[rawfile->name] = std::make_unique<char[]>(num_bytes_read + 1);
or actually std::string? std::unique_ptr<std::string>?

2022-10-20 06:16 UTC, momo5502 commented on src/client/component/assets/rawfile.cpp
> +			rawfile_entry_buffer[num_bytes_read] = '\0';
yep, if you use std::string then you don't need this. .data() automatically appends nullterminator

2022-10-20 16:35 UTC, JezuzLizard commented on src/client/component/assets/rawfile.cpp
> +REGISTER_COMPONENT(assets::rawfile::component)
Yeah I guess it doesn't need to be a component but I think it should be in its own file because I intend on adding more assets in the future so putting it in its own file makes sense because it prevents clutter.

2022-10-21 16:59 UTC, ineedbots commented on src/client/component/assets/rawfile.cpp
> +			rawfile_entry_buffer[num_bytes_read] = '\0';
isnt that what .c_str() does?  .data() is only going to be the data buffer to the std::string, so it may not have a null char

2022-10-21 17:09 UTC, diamante0018 commented on src/client/component/assets/rawfile.cpp
> +			rawfile_entry_buffer[num_bytes_read] = '\0';
That is wrong for std::string
.data and c_string have had the same meaning for many c++ standards iterations

2022-10-21 17:24 UTC, ineedbots commented on src/client/component/assets/rawfile.cpp
> +			rawfile_entry_buffer[num_bytes_read] = '\0';
Assumes that the compiler is adhering to the standard, it IS left up to compiler implementation, but in the case of MSVC, they do the same thing

2022-10-21 17:27 UTC, diamante0018 commented on src/client/component/assets/rawfile.cpp
> +			rawfile_entry_buffer[num_bytes_read] = '\0';
That's unjustified misplaced trust, MSVC STL implementation is here: https://github.com/microsoft/STL

you are probably looking for your non-existent non compliant implementation of std::string in the xstring header

(sorry for being blunt)

2022-10-22 08:17 UTC, momo5502 commented on src/client/component/assets/rawfile.cpp
> +REGISTER_COMPONENT(assets::rawfile::component)
but the component folder is definitely the wrong place, if it's not a component

2022-10-22 08:21 UTC, momo5502 commented on src/client/component/assets/rawfile.cpp
> +			rawfile_entry_buffer[num_bytes_read] = '\0';
> isnt that what .c_str() does? .data() is only going to be the data buffer to the std::string, so it may not have a null char

Since C++11 both are the same ( https://en.cppreference.com/w/cpp/string/basic_string/data ). Therefore I prefer data

2022-10-22 08:24 UTC, momo5502 commented on src/client/component/assets/rawfile.cpp
> +			rawfile_buffers[rawfile->name] = std::make_unique<std::string>();
can resize the buffer you read into and directly move it into the make_unique construction sequence

2022-10-22 08:25 UTC, momo5502 commented on src/client/component/assets/rawfile.cpp
> +			rawfile_buffer->assign(buffer, num_bytes_read);
instead of copying here

2022-10-22 17:33 UTC, JezuzLizard commented on src/client/component/assets/rawfile.cpp
> +REGISTER_COMPONENT(assets::rawfile::component)
Ah I see yeah I'll move it out of components. client\game\assets or client\assets then maybe.

2023-02-05 12:54 UTC, momo5502 commented
The topic of this PR is sadly slightly more complicated than it seemed at first.
This PR does not meet the standarts of the project, yet.
As no actions have been taken recently, I'm closing it, but it can be reopend if changes are willing to be made.

2023-02-05 12:54 UTC, closed without merging