fix: support for hardcore on the server browser
momo5502/boiii pull request #494
Opened 2023-04-10 22:30 UTC by JariKCoding

Added support for the hardcore skull icon in the server browser
![image](https://user-images.githubusercontent.com/23278562/231011215-10294593-2988-417b-969e-c3ad355ece07.png)

2023-04-10 22:32 UTC, diamante0018 commented on src/client/component/getinfo.cpp
> +				info.set("hc", utils::string::va("%i", game::Com_GametypeSettings_GetUInt("hardcoremode", false)));
now that i think of it, why is utils::string::va being used this much in this file when std::to_string exists? 😂 
probably a question for another day, patch looks good.

2023-04-10 22:33 UTC, diamante0018 requested changes

2023-04-10 22:42 UTC, diamante0018 approved these changes

2023-04-11 04:18 UTC, momo5502 commented on src/client/component/getinfo.cpp
> +				info.set("hc", utils::string::va("%i", game::Com_GametypeSettings_GetUInt("hardcoremode", false)));
that really screams like good old c&p 😂

2023-04-11 09:51 UTC, diamante0018 commented
@momo5502 could u merge this so i can then make a new pr for ::va?

2023-04-11 09:55 UTC, momo5502 commented
> @momo5502 could u merge this so i can then make a new pr for ::va?
> Or you wanted myself or jarik do address it right away?

you uave to close open comments i think. cant see it on my phone

2023-04-11 09:56 UTC, merged