Allow access to online menus with mod loaded
momo5502/boiii pull request #510
Opened 2023-04-11 22:10 UTC by WantedDV

closes #414

2023-04-12 09:09 UTC, diamante0018 requested changes
snake case the lua file names.

2023-04-20 21:02 UTC, JariKCoding approved these changes

2023-04-22 02:09 UTC, diamante0018 commented
> Closes #414

You need to add the closes keyword to your mail post at the top of this pull request otherwise it will not link the issue.

2023-04-24 16:55 UTC, momo5502 approved these changes

2023-04-24 16:56 UTC, merged