Mods support for dedicated servers
momo5502/boiii pull request #513
Opened 2023-04-12 14:55 UTC by Brentdevent

- Client auto loads the same mod as the server is running, upon connection
- Mod name is read from the workshop.json and send to client to visualize the mod name in the serverbrowser

**Important note**: The mod name varies in size since `m_szGameTags` has a max buffer size of 128 characters. So because of the gametype and the other parameters it causes the mod name to be shortened to the available size that is left. The buffer is just way to small, it seems kinda tedious to increase this. Atleast I don't see an easy way.

This also seems to occur on the steam version, so I guess it should be fine for now.
 
Dedicated servers were already able to load mods by using the following path: `Call of Duty Black Ops III\UnrankedServer\mods\<publisher_id>\zone`

Closes issue https://github.com/momo5502/boiii/issues/488

Some files contain wrong line endings, I did not change it. To make this PR more easier to read.
And I assume this belongs to a different PR.

2023-04-13 09:18 UTC, diamante0018 requested changes

2023-04-13 09:18 UTC, diamante0018 commented on src/client/component/workshop.cpp
> +	const std::string get_mod_name(const std::string& mod_id)
remove const, it prevents optimizations.

2023-04-13 09:20 UTC, diamante0018 commented on src/client/component/workshop.cpp
> +	const std::string get_usermap_publisher_id(const std::string& mapname)
Same here as well.
And source: https://clang.llvm.org/extra/clang-tidy/checks/readability/const-return-type.html

2023-04-13 09:34 UTC, Brentdevent commented on src/client/component/workshop.cpp
> +	const std::string get_usermap_publisher_id(const std::string& mapname)
Oh interesting learned something new, thank you!

2023-04-13 09:56 UTC, diamante0018 requested changes

2023-04-13 09:56 UTC, diamante0018 commented on src/client/component/workshop.cpp
> +		doc.Parse(json_str);
I strongly advise to catch parse errors like this: https://github.com/XLabsProject/master/blob/master/src/patreon.cpp#L23

2023-04-13 15:48 UTC, momo5502 approved these changes

2023-04-13 15:59 UTC, momo5502 requested changes

2023-04-13 15:59 UTC, momo5502 commented on src/client/component/workshop.cpp
> +		utils::io::read_file(path, &json_str);
there is a shorter read_file that directly returns a string
```suggestion
		std::string json_str = utils::io::read_file(path);
```

2023-04-13 15:59 UTC, momo5502 commented on src/client/component/workshop.cpp
> +		}
why no early return here?

```suggestion
		if (!game::is_server())
		{
			return mod_id;
		}
		
		const utils::nt::library host{};
		const auto base_path = host.get_folder().generic_string();
		std::string path = utils::string::va("%s/mods/%s/zone/workshop.json", base_path.data(), mod_id.data());
```

2023-04-13 15:59 UTC, momo5502 commented on src/client/component/workshop.cpp
> +		utils::io::read_file(path, &json_str);
or you respect the return value of your current read_file call. it returns a bool whether reading was successful or not

2023-04-13 15:59 UTC, momo5502 commented on src/client/component/workshop.cpp
> +		}
you can remove the else scope here, as the if has a return statement
```suggestion

		printf("[ Workshop ] workshop.json has no \"Title\" member.\n");
		return mod_id;
```

2023-04-13 15:59 UTC, momo5502 commented on src/client/component/workshop.cpp
> +			const auto usermap_data = reinterpret_cast<game::workshop_data*>(0x1567B3588_g + (sizeof(game::workshop_data) * i));
this code only runs either on client or on dedi, not sure. wouldn't it be desirable to have it work for both?

2023-04-13 15:59 UTC, momo5502 commented on src/client/component/workshop.cpp
> +			game::Com_Error(0, "Can't find mod with publisher id: %s!\nMake sure you're subscribed to the workshop item.", mod.data());
Com_Error is super evil. please don't use it. it prevents object destruction and thus casues memory leaks as it unwinds the stack in an unclean way, at least legacy setjmp implementations don't do proper unwinding.

2023-04-13 18:18 UTC, Brentdevent commented on src/client/component/workshop.cpp
> +			const auto usermap_data = reinterpret_cast<game::workshop_data*>(0x1567B3588_g + (sizeof(game::workshop_data) * i));
It runs only on the client yea, due we're using a non steam method for dedicated servers to load user content. This data section doesn't contain the publisherId.

But I have been thinking about using the publisherId as folder name for usermaps too. But this most likely require some more changes so perhaps this something for another PR.

2023-04-14 07:14 UTC, Brentdevent commented
> > But I have been thinking about using the publisherId as folder name for usermaps too. But this most likely require some more changes so perhaps this something for another PR.
> 
> If using publisherId as folder name is the best way to go then we should probably update the ui so it still shows mod names instead of this: ![image](https://user-images.githubusercontent.com/122710241/231884851-e0fadd97-e9dd-4f22-bfc5-acdc105901f4.png) Similar for usermaps if you make that change. This is probably something I can do.
> 
> The only other downside is that content in these folders will be not easily identifiable unless you open up the workshop file in each folder to see what it is. At the same time though, this is how steam does it.

Well I'm still not certain about a few things, should we support add mod/usermaps support for non-steam copies to play online? 

Maybe a better alternative would be to iterate through the steam workshop folder and add the content ourselves to the usermap and mods data pool whenever steam is not detected.

But this will be pointless to implement at the moment if there will be steam check later.

Also would it be desirable for server owners to install steam on their VPS to download workshop content? Or should we stick with the current method we're using to load usercontent.

I have to admit the current implementation of the mod support is not ideal for non-steam copies indeed. Honestly I haven't even tested it. So I'm not even certain if it'll work for them.

2023-04-14 12:11 UTC, momo5502 approved these changes

2023-04-14 12:13 UTC, momo5502 commented
Anything else? @WantedDV @Brentdevent ? Do you think changes are still needed?

2023-04-14 13:22 UTC, Brentdevent commented
Should be fine for now, I'll look into a way to improve it for offline use since I understand the concerns. Not entirely sure yet what route I'll be taking. But I'll improve it in a later PR. I have some ideas but I'll have to see which one will be a better one.

It makes things a lot more complicated, to keep it working in a clean way but to satisfy both ways of loading user content.

2023-04-14 17:38 UTC, diamante0018 approved these changes

2023-04-15 12:07 UTC, merged