feat: add support for favorites in the server browser
momo5502/boiii pull request #519
Opened 2023-04-12 21:46 UTC by JariKCoding

Writes favorited servers to players/user/favorite_servers.csv

![image](https://user-images.githubusercontent.com/23278562/231593032-8da1c197-c212-4fe9-8ff8-c32ef1cdc5ce.png)

2023-04-13 07:28 UTC, momo5502 commented on src/client/component/server_list.cpp
> +				servers_buffer.append(utils::string::va("%u,%u\n", itr.addr, itr.port));
why use a csv and not just directly store 127.0.0.1:27017 in every line
then you can just split the lines and directly pass the line to network::address_from_string or whateever it's called

2023-04-13 15:47 UTC, momo5502 requested changes

2023-04-13 15:47 UTC, momo5502 commented on src/client/component/server_list.cpp
> +				servers_buffer.append(utils::string::va("%u,%u\n", itr.addr, itr.port));
why use a csv and not just directly store 127.0.0.1:27017 in every line
then you can just split the lines and directly pass the line to network::address_from_string or whateever it's called

2023-04-15 11:57 UTC, momo5502 commented on src/client/component/server_list.cpp
> +			}, scheduler::main);
loop? are you sure you want an infinite loop that fires every frame?

2023-04-15 11:59 UTC, momo5502 commented on src/client/component/server_list.cpp
> +	bool has_favorited_server(game::netadr_t addr)
const game::netadr_t&

2023-04-15 12:01 UTC, momo5502 commented on src/client/component/server_list.cpp
> +		std::vector<game::netadr_t> favorite_servers{};
i recommend using an unordered_set instead of a vector, that implicitly gets rid of the need of all duplication checks

2023-04-15 12:05 UTC, momo5502 commented on src/client/steam/interfaces/matchmaking_servers.cpp
> +							}
so you query all servers and filter out all but the favorites. interesting. should be fine for now, but on the long run i recommend querying only the favorites

2023-04-15 19:57 UTC, JariKCoding commented on src/client/steam/interfaces/matchmaking_servers.cpp
> +							}
I've changed it so it only queries your favorites. I've also made some big changes to keep the lists seperate so when switching between tabs fast internet servers don't end up on the favorites tab.

2023-04-16 08:21 UTC, momo5502 requested changes

2023-04-16 08:21 UTC, momo5502 commented on src/client/component/server_list.cpp
> +	std::unordered_set<game::netadr_t>* get_favorite_servers()
std::unordered_set<game::netadr_t>&

no need to return a pointer here, just return a ref

2023-04-17 05:53 UTC, momo5502 commented on src/client/component/server_list.cpp
> +	}
i have one last question here, are you sure this set is not used by multiple threads? from looking at the code i think it's safe, but can you maybe cofirm that? maybe even verify that? or should we wrap it in a concurrency container? just to be safe to avoid any races?

2023-04-24 11:21 UTC, momo5502 approved these changes

2023-04-24 11:22 UTC, merged