Improve mod/usermap support
momo5502/boiii pull request #558
Opened 2023-04-18 17:50 UTC by Brentdevent

- Better support for offline usermap/mods loading, You are now able to just copy & paste the workshop folder in the usermaps/mods folder. The additional zone folder is no longer used.
- workshop.json data gets written to usermaps/mods pool and is required to make it work correctly to play online.  Without it should still work but folder names need to be synced could still be useful for mod developers. But it will print out a warning to console since the publisherId will not be numerical in this case.
- Mods/usermaps which are loaded offline now show up in the menus with the correct data just like the ones from steam workshop.
- This allows dedicated servers to rename their folders to whatever they want, although it seems this causes issues with some mods for unknown reasons. For example I got a clientField mismatch with the mod called mwz_lite after renaming the folder from publisherID to mwz_lite. I assume it has something to do with mod itself since with another mod this doesn't occur.

2023-04-18 18:08 UTC, momo5502 reviewed
looks good at first sight, but will do an in-depth review tomorrow

2023-04-20 16:37 UTC, momo5502 requested changes
Honestly impressed by the code you write. It gets cleaner and cleaner with every PR. Very cool :)
Still a few remarks 😂 But only minor things

2023-04-20 16:37 UTC, momo5502 commented on src/client/component/party.cpp
> +			{
why? xD

2023-04-20 16:37 UTC, momo5502 commented on src/client/component/workshop.cpp
> +		void load_usermap_content_stub(void* usermapsCount, int type)
where snake case bro? usermapsCount?

2023-04-20 16:37 UTC, momo5502 commented on src/client/component/workshop.cpp
> +				load_workshop_data(usermap_data);
am i wrong or don't you need a break afterwards?

2023-04-20 16:37 UTC, momo5502 commented on src/client/component/workshop.cpp
> +				load_workshop_data(mod_data);
break?

2023-04-20 16:37 UTC, momo5502 commented on src/common/utils/string.cpp
> +	}
while your code is correct, i always used std::to_string(atoi(text.data())) == text
has a heap allocation (probably not with sso) which yours doesn't but it's a super concise one liner. but yours is probably better. just as a hint

2023-04-20 20:33 UTC, Brentdevent commented on src/client/component/workshop.cpp
> +				load_workshop_data(usermap_data);
Nah, I'm iterating over every usermap/mod, check if it's loaded from the usermaps/mods folder if so I load the data from the corresponding workshop.json.

2023-04-20 20:33 UTC, Brentdevent commented on src/client/component/workshop.cpp
> +				load_workshop_data(mod_data);
See the other reply.

2023-04-20 20:35 UTC, Brentdevent commented on src/client/component/workshop.cpp
> +		void load_usermap_content_stub(void* usermapsCount, int type)
Good catch, sorry oversight, tend to make this mistake by switching between IDA and vs haha

2023-04-20 20:36 UTC, Brentdevent commented on src/client/component/party.cpp
> +			{
Performance improvements 😎 nah kidding, missed this change.

2023-04-20 20:38 UTC, Brentdevent commented on src/common/utils/string.cpp
> +	}
Yea I did the same at first, untill I noticed that the publisherID's are bigger than the max size of an integer. So I went with this implementation. I was not aware of the existence of stoul at the time. If you want I can change it. It's whatever you prefer.

2023-04-24 11:23 UTC, momo5502 commented
Has conflicts. If you resolve them, we can merge it :)

2023-04-24 11:24 UTC, momo5502 approved these changes

2023-04-24 12:41 UTC, Brentdevent commented
I changed one more thing, it was possible for clients to load a mod and join a non-modded server, so I do an additional check and unload the mod if this is the case.

2023-04-24 16:53 UTC, merged

2023-04-24 16:55 UTC, diamante0018 commented on src/client/component/workshop.cpp
> +			item.publisherIdInteger = std::stoul(item.publisherId);
Potentially unsafe as this function will throw if it can't parse the input and cause a crash

2023-04-24 16:57 UTC, diamante0018 commented on src/common/utils/string.cpp
> +	{
Type is size_t so <= 0 is not correct as it can't never be less than 0. Check for empty