fix: only load the gsc files with the right magic
momo5502/boiii pull request #647
Opened 2023-05-04 21:24 UTC by JariKCoding

2023-05-05 08:37 UTC, diamante0018 requested changes

2023-05-05 08:37 UTC, diamante0018 commented on src/client/component/script.cpp
> +				if (!std::filesystem::is_directory(script) && utils::io::read_file(script_file, &data) && *(uint64_t*)data.c_str() == 0x1C000A0D43534780)
Feels kinda hacky. We do not use c_str but rather we use data. Then this is a C cast rather than a C++ style cast.
Would suggest breaking this out in a new if statement.
Also you should probably use https://en.cppreference.com/w/cpp/string/byte/memcmp

2023-05-05 08:40 UTC, diamante0018 commented on src/client/component/script.cpp
> +				if (!std::filesystem::is_directory(script) && utils::io::read_file(script_file, &data) && *(uint64_t*)data.c_str() == 0x1C000A0D43534780)
also define the magic as a constexpr value somewhere so we can infer by the name that this random number is supposed to be "GSC_MAGIC" or something like that

2023-05-05 08:43 UTC, momo5502 commented on src/client/component/script.cpp
> +				if (!std::filesystem::is_directory(script) && utils::io::read_file(script_file, &data) && *(uint64_t*)data.c_str() == 0x1C000A0D43534780)
i aggree with the GSC magic. also make sure the endianness is correct. and most importantly data.size() >= sizeof(GSC_MAGIC).

2023-05-06 10:08 UTC, diamante0018 approved these changes
Great job

2023-05-06 19:48 UTC, momo5502 commented
will merge tomorrow

2023-05-07 09:42 UTC, momo5502 approved these changes

2023-05-07 09:42 UTC, merged