ZM: Make Super EE reward compatibility opt-in in mods.
momo5502/boiii pull request #675
Opened 2023-05-09 18:24 UTC by MotoLegacy

(Fixes #469)
A consequence of boiii's Online Service emulation carrying over to loaded mods was the RK5 starting weapon causing issues with various ZM maps. If a map/mod already had a second starting weapon defined and applied, the `level.super_ee_weapon` would still get appended, and would cause the "Samantha" effect to trigger. Additionally, levels with custom HUDs via LUI or similar may have certain visualizations of their weapon set (e.g. Daybreak's weapon portraits taken from Black Ops 4) would just display something broken in its place.

This change alleviates this by not removing the feature entirely in loaded mods, but instead making it opt-in, via a new level flag, `level.modSupportsSuperEERewards`. This way a mod creator can evaluate themselves if they want their content to support the weapon for reward holders, and may also encourage them to define their own Super EE weapon themselves by changing the value of `level.super_ee_weapon`.

The change overrides `Callback_PlayerConnect()` in `scripts/zm/gametypes/_globallogic_player`. It was evaluated to be the best location for the change, as it is unlikely to be overridden by a mod to unintentionally break the change, as well as being the place that triggers the stat updating that would define whether or not the player has completed all main quests.

The actual change to the script follows:

```c
// MotoLegacy (09 MAY 2023) -- Super Easter Egg Override START
// Mod creators can use this field to opt-into the Super EE start weapon
if (!IsDefined(level.modSupportsSuperEERewards))
    level.modSupportsSuperEERewards = false;

// No rewards if a mod is loaded and mod creator has not permitted RK5 start.
if (GetDvarString("fs_game") != "" && level.modSupportsSuperEERewards == false)
    self.hasCompletedSuperEE = false;
// MotoLegacy (09 May 2023) -- super Easter Egg Override END
```

2023-05-09 19:23 UTC, diamante0018 requested changes

2023-05-09 19:23 UTC, diamante0018 commented on data/scripts/zm/gametypes/_globallogic_player.gsc_raw
> +		level.modSupportsSuperEERewards = false;
Please follow 3arc meme GSC convention:
For example this block should be formatted `if ( getDvarString( "...") )` with the spaces .
I suppose the rest of the files already follows this convention.
You only need to edit the raw file.

2023-05-09 19:34 UTC, MotoLegacy commented
@diamante0018 I have resolved (at least, I think... that convention is whack) the Treyarch GSC convention discrepancy.

2023-05-09 19:48 UTC, diamante0018 approved these changes

2023-05-09 20:12 UTC, mjkzy approved these changes
nice PR

2023-05-09 21:10 UTC, efinst0rm commented
Where is this gsc from? If its from modtools it might be out of date compared to what's used in production.

2023-05-09 21:15 UTC, MotoLegacy commented
> Where is this gsc from? If its from modtools it might be out of date compared to what's used in production.

We've talked about this in the Discord — waiting on Serious to confirm it's good but from a skim it seems to match production (yes, it is sourced from the Mod Tools release).

2023-05-13 15:55 UTC, MotoLegacy commented
Okay, sure thing. For now I will convert this to a draft PR so people know there is a fix ready, and when the GSC PR is merged I will go ahead and clean up these commits and re-implement it using a custom script.

2023-05-21 17:06 UTC, closed without merging