custom GSC loading
momo5502/boiii pull request #689
Opened 2023-05-13 02:45 UTC by mjkzy

2023-05-13 17:05 UTC, momo5502 commented on src/client/component/script.cpp
> +			game::Scr_LoadScript(game::SCRIPTINSTANCE_SERVER, name.substr(0, name.size() - 4).data()); // .gsc suffix will be readded by Scr_LoadScript
what if name.size() < 4?

2023-05-13 17:07 UTC, momo5502 commented on src/client/component/script.cpp
> +		utils::hook::detour load_gametype_script_hook;
imo we should try to avoid detours whenever possible and use call hooks instead. detours can break if there are rip-relative instructions within the range of the trampoline

2023-05-13 21:12 UTC, mjkzy commented on src/client/component/script.cpp
> +		utils::hook::detour load_gametype_script_hook;
yeah, the hook is not really needed since this is only called once. i'll clean it up later - this had just been a rushed thing :D

2023-05-14 07:53 UTC, momo5502 commented
the pr looks quite good. why is it still draft?

2023-05-14 07:54 UTC, momo5502 commented on src/client/component/script.cpp
> +			if (base_name.size() < 1)
```suggestion
			if (base_name.empty())

```

2023-05-14 08:04 UTC, mjkzy commented
forgot to change it from a draft

2023-05-14 08:29 UTC, diamante0018 reviewed
I have a feeling this pr will introduce a massive memory leak

The allocator is never freed

2023-05-14 08:29 UTC, diamante0018 commented on src/client/component/script.cpp
> +			if (utils::string::ends_with(name, ".gsc"))
If the extension is not .GSC you should probably return I think

2023-05-14 08:29 UTC, diamante0018 requested changes
I have a feeling this pr will introduce a massive memory leak

The allocator is never freed

2023-05-14 08:31 UTC, mjkzy commented on src/client/component/script.cpp
> +			if (utils::string::ends_with(name, ".gsc"))
good call idk why i dont just reutrn lmfao

2023-05-14 08:33 UTC, diamante0018 commented
It's possible the memory leak already exists on prod boiii right now.
I think it's missing a hook in g_shutdown game to free the scripts

2023-05-14 09:04 UTC, diamante0018 approved these changes
lgtm

2023-05-14 13:37 UTC, Aziks0 commented
The file updater nukes everything in the `data` folder, except the ones listed in `https://updater.xlabs.dev/boiii.json`, so you should whitelist the `data/custom-scripts` folder.

And btw, you used snake cases for `lookup_tables` and `ui_scripts`, so I guess `custom_scripts` might be a better name.

2023-05-14 13:42 UTC, diamante0018 commented
> The file updater nukes everything in the `data` folder, except the ones listed in `https://updater.xlabs.dev/boiii.json`, so you should whitelist the `data/custom-scripts` folder.
> 
> And btw, you used snake cases for `lookup_tables` and `ui_scripts`, so I guess `custom_scripts` might be a better name.

No. The folder is reversed for your use.
You should use the boiii folder

2023-05-14 14:20 UTC, diamante0018 approved these changes

2023-05-14 16:09 UTC, momo5502 requested changes

2023-05-14 16:31 UTC, diamante0018 commented on src/client/component/game_event.cpp
> +		std::vector<std::function<void()>> g_init_game_tasks_;
guaranteed yes

2023-05-14 16:33 UTC, diamante0018 commented on src/client/game/structs.hpp
> +		unsigned __int16 classnum;
done

2023-05-15 16:29 UTC, momo5502 commented on src/client/component/game_event.cpp
> +		std::vector<std::function<void()>> g_init_game_tasks_;
as you are providing it as a generic api through a separate component, you can not guarantee it. please use a concurrency container

2023-05-15 16:32 UTC, momo5502 requested changes
concurrency container and it seems fine to me

2023-05-15 19:09 UTC, momo5502 commented
> > concurrency container and it seems fine to me
> 
> why? there should not be any need. functions are always called from game thread.

as i already said, you are exposing this as an api. anyone can include game_event.hpp and access that api. maybe right now you can guarantee thread safety. but anyone using that in the future can suffer from issues. and we will have a hard time debugging. as you decided to model the game events as a general api, we should guarantee thread safety, in my opinion.

2023-05-16 04:34 UTC, momo5502 approved these changes

2023-05-16 04:35 UTC, momo5502 commented
skipping the ci for the last commit was not the best idea, but i'll just force merge and we pray it compiles :P

2023-05-16 04:35 UTC, merged

2023-05-20 00:18 UTC, ineedbots commented on src/client/component/script.cpp
> +			load_scripts_folder((data_folder / "scripts").string(), false);
you forgot gamemode and map specific folders 😭

2023-05-20 09:07 UTC, diamante0018 commented on src/client/component/script.cpp
> +			load_scripts_folder((data_folder / "scripts").string(), false);
Noob add them

2023-05-20 09:26 UTC, mjkzy commented on src/client/component/script.cpp
> +			load_scripts_folder((data_folder / "scripts").string(), false);
we just didn't care to add them for the time being but we'll get around to it eventually

2023-05-20 10:40 UTC, diamante0018 commented on src/client/component/script.cpp
> +			load_scripts_folder((data_folder / "scripts").string(), false);
You actually left a review. SMH