fix(server_status): format it properly
momo5502/boiii pull request #690
Opened 2023-05-13 09:36 UTC by diamante0018

bot0 required for consistency between our clients and plutonium as the bot's guid is usually bot%d (%d replaced by qport)
This is not possible currently so just like I've done on plutonium t5 it's just bot0
Then i fixed the status header

2023-05-13 17:04 UTC, momo5502 commented on src/client/component/status.cpp
> +			                         "num score ping guid             name             address                  qport  \n");
original status says xuid, doesn't it?

2023-05-13 17:04 UTC, diamante0018 commented on src/client/component/status.cpp
> +			                         "num score ping guid             name             address                  qport  \n");
our clients have guid. storm asked me to rename but you would be correct. the original status says xuid

2023-05-13 17:05 UTC, momo5502 commented on src/client/component/status.cpp
> +			                         "num score ping guid             name             address                  qport  \n");
note there is two status handlers in the client, one that says guid and the one that says xuid. i think the one with xuid is the one that's actively used. so make sure you base this on the proper on

2023-05-13 17:05 UTC, diamante0018 commented on src/client/component/status.cpp
> +			                         "num score ping guid             name             address                  qport  \n");
I made sure this is the one that prints into the console when i type status command in my in-game console

2023-05-13 17:11 UTC, diamante0018 commented on src/client/component/status.cpp
> +			                         "num score ping guid             name             address                  qport  \n");
i renamed it back to xuid so it stays consistent. but this should be the correct status handler between the two

2023-05-13 19:42 UTC, momo5502 commented on src/client/component/status.cpp
> +			                         "num score ping guid             name             address                  qport  \n");
perfect, just wanted to make sure.

2023-05-13 19:43 UTC, momo5502 approved these changes

2023-05-13 19:44 UTC, momo5502 requested changes

2023-05-13 19:44 UTC, momo5502 commented on src/client/component/status.cpp
> +		int client_num_;
i recommend this to be thread_local

2023-05-13 19:45 UTC, momo5502 commented on src/client/component/status.cpp
> +		int client_num_;
even though technically it's not really necessary,calling the status command from different threads concurrently could yield errors. we know this is not gonna happen, but using thread_local still seems to be a good practice in that case

2023-05-13 19:47 UTC, diamante0018 commented on src/client/component/status.cpp
> +		int client_num_;
done

2023-05-14 07:10 UTC, momo5502 approved these changes

2023-05-14 07:10 UTC, merged